/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.HeadlessException;
import  java.sql.*;
import java.sql.Connection;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JProgressBar;
import javax.swing.JTextField;

/**
 *
 * @author Abhinav
 */
public class Reciverdetails extends javax.swing.JFrame {

    /**
     * Creates new form Reciverdetails
     */
    
    JFrame refFrame;
    String pwdString;
    String acbalString;
    String acidString;
    String nameString;
    public Reciverdetails() {
        initComponents();
    }
     public Reciverdetails(JFrame tempFrame,String pwdString,String acbalString,String acidString,String nameString) {
        initComponents();
        refFrame=tempFrame;
        this.acbalString=acbalString;
        this.pwdString=pwdString;
        this.acidString=acidString;
        this.nameString=nameString;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acnotxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        btnhome = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        amttxt = new javax.swing.JTextField();
        btnsubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Enter Recipent's Details ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Recipent's Name:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Account No");

        acnotxt.setForeground(new java.awt.Color(0, 0, 0));
        acnotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acnotxtActionPerformed(evt);
            }
        });

        nametxt.setForeground(new java.awt.Color(0, 0, 0));
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        btnhome.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnhome.setForeground(new java.awt.Color(0, 0, 0));
        btnhome.setText("<< HOME");
        btnhome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnhome.setOpaque(true);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Amount :");

        amttxt.setForeground(new java.awt.Color(0, 0, 0));
        amttxt.setText("300");

        btnsubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnsubmit.setForeground(new java.awt.Color(0, 0, 0));
        btnsubmit.setText("Submit");
        btnsubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(acnotxt)
                                    .addComponent(nametxt)
                                    .addComponent(amttxt, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhome))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void acnotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acnotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acnotxtActionPerformed

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
        refFrame.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnhomeActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:
          String  id=acnotxt.getText();
        Double amounttrans=Double.parseDouble(amttxt.getText());
          Double amountavalable=0.0;
        Double recipacbalDouble;
        String recipent_nameString=nametxt.getText();
        try {
               Connection connection= CommonFunction.addConection();
            String querystrString="select * from accounts where Account_ID= "+acidString;
            Statement statement=connection.createStatement();
            ResultSet resultSet;
            resultSet=statement.executeQuery(querystrString);
            if(resultSet.first())
            {
                amountavalable=Double.parseDouble(resultSet.getString("account_bal"));
            }
            
            
        } catch (Exception e) 
        {
            System.out.println("error "+e);
        }
        
      
       
      
     
       
        if(amounttrans>amountavalable)
        {
            JOptionPane.showMessageDialog(null, "Insufficient Balance","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
               
            try {
            Connection connection= CommonFunction.addConection();
            String querystrString="select * from accounts where Account_ID= "+id;
            Statement statement=connection.createStatement();
            ResultSet resultSet;
            resultSet=statement.executeQuery(querystrString);
            if(resultSet.first())
            {
                recipacbalDouble=Double.parseDouble(resultSet.getString("account_bal"));
                String passwordString;
                JPasswordField pfField=new JPasswordField();
                int ans=JOptionPane.showConfirmDialog(this, pfField, "Enter Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
                if (ans == JOptionPane.OK_OPTION)
                {
                        passwordString= new String(pfField.getPassword());
                        System.out.println("User pasword is "+pwdString+"\n");
                        
                        if(passwordString.equals(""))
                        {
                            JOptionPane.showMessageDialog(this, "Password field is empty","Error",JOptionPane.ERROR_MESSAGE);
                        }
                        else
                        {
                            if(passwordString.equals(pwdString))
                            {
                                updateBalanceandInsertTrans(amountavalable,amounttrans,id,recipacbalDouble);
                                progressbar obj=new progressbar(this,refFrame);
                                obj.setVisible(true);
                                
                          //      refFrame.setVisible(true);
                             //   dispose();
                            }
                            else
                            {
                                JOptionPane.showMessageDialog(this,"Incorrect Password","Error",JOptionPane.ERROR_MESSAGE);
                                //here validation  no of wrong attempt can be done
                            }
                        }
                
                
                 }
                
                
                
                
            }   
            else
            {
                JOptionPane.showMessageDialog(this, "Inavalid Ac Number","Error",JOptionPane.ERROR_MESSAGE);
            }
            }
            catch (HeadlessException | SQLException e) 
            {
            System.out.println("Error"+e);
            }
            
            
        }
        
        
    }//GEN-LAST:event_btnsubmitActionPerformed
     private void updateBalanceandInsertTrans(Double acbalofsender,Double transamount ,String id,Double recipentbal)
     {
         //acidstring is sender
         //id is reciver
         // amttxt is amouunt of transation 
            Calendar cal=Calendar.getInstance();
          java.util.Date date=cal.getTime();
            SimpleDateFormat formatter1 = new SimpleDateFormat("yyyy/MM/dd");  
            String dateString= formatter1.format(date); 
        
         String senderbal=String.valueOf(acbalofsender-transamount);
         String recipentbalString=String.valueOf(transamount+recipentbal);
         
         System.out.println("Sender balance is "+senderbal+"\n Recipnt balance is "+recipentbalString);
       //  System.out.println(amtString);
         
         try {
             Connection connection=CommonFunction.addConection();
            
             Statement statement=connection.createStatement();
             
             String queryString="update accounts set account_bal= '"+senderbal+"' where Account_ID='"+acidString+"' ";
             statement.executeUpdate(queryString);
             //
              queryString="update accounts set account_bal= '"+recipentbalString+"' where Account_ID='"+id+"' ";
              statement.executeUpdate(queryString);
              
             queryString="INSERT INTO `bank_system`.`transactions` ( `date`, `amount`, `Account_ID_sender`, `Account_ID_reciver`, `Recipent's name`, `Status`)"
                     + " VALUES ( '"+dateString+"', '"+transamount+"', '"+acidString+"', '"+id+"', '"+nametxt.getText()+"', 'Sent')";
             statement.executeUpdate(queryString);
             
             
              queryString="INSERT INTO `bank_system`.`transactions` ( `date`, `amount`, `Account_ID_sender`, `Account_ID_reciver`, `Recipent's name`, `Status`)"
                     + " VALUES ( '"+dateString+"', '"+transamount+"', '"+id+"', '"+acidString+"', '"+nameString+"', 'Recived')";
             statement.executeUpdate(queryString);

              
              
             
             
             
             
             
         } catch (Exception e)
         {
             System.out.println("Error" +e);
         }
     }
    public Reciverdetails(JFrame refFrame, String pwdString, String acbalString, JTextField acnotxt, JTextField amttxt, JButton btnhome, JButton btnsubmit, JLabel jLabel1, JLabel jLabel2, JLabel jLabel3, JLabel jLabel4, JPanel jPanel1, JTextField nametxt) throws HeadlessException {
        this.refFrame = refFrame;
        this.pwdString = pwdString;
        this.acbalString = acbalString;
        this.acnotxt = acnotxt;
        this.amttxt = amttxt;
        this.btnhome = btnhome;
        this.btnsubmit = btnsubmit;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jLabel4 = jLabel4;
        this.jPanel1 = jPanel1;
        this.nametxt = nametxt;
    }

    
    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reciverdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reciverdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reciverdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reciverdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reciverdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acnotxt;
    private javax.swing.JTextField amttxt;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nametxt;
    // End of variables declaration//GEN-END:variables
}
