/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import javax.swing.JFrame;

/**
 *
 * @author Abhinav
 */
    
public class Transfermoney extends javax.swing.JFrame implements  Runnable
{

    /**
     * Creates new form Transfermoney
     * 
     */
    JFrame refFrame;
    String pwdString;
    String acbalString;
    String acidString;
    String nameString;
    public Transfermoney() {
        initComponents();
        CommonFunction.addLabelBackground(lblmoneytrans, "D:\\JAVA_awt\\GUI\\Bank_System\\src\\main\\java\\mypackage\\images\\moneytrans.png");
        CommonFunction.addLabelBackground(lbltranshis, "D:\\JAVA_awt\\GUI\\Bank_System\\src\\main\\java\\mypackage\\images\\transhistory.png");
         Thread t=new Thread(this);
        t.start();
    }
      public Transfermoney(JFrame tempFrame,String pwdString,String acbalString,String acidString,String name) {
        initComponents();
        CommonFunction.addLabelBackground(lblmoneytrans, "D:\\JAVA_awt\\GUI\\Bank_System\\src\\main\\java\\mypackage\\images\\moneytrans.png");
        CommonFunction.addLabelBackground(lbltranshis, "D:\\JAVA_awt\\GUI\\Bank_System\\src\\main\\java\\mypackage\\images\\transhistory.png");
        
        refFrame=tempFrame;
        this.pwdString=pwdString;
        this.acbalString=acbalString;
        this.acidString=acidString;
        this.nameString=name;
        Thread t=new Thread(this);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnhome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btntranshis = new javax.swing.JButton();
        lbltranshis = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btntransmoney = new javax.swing.JButton();
        lblmoneytrans = new javax.swing.JLabel();
        lblnote = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        btnhome.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        btnhome.setForeground(new java.awt.Color(0, 0, 0));
        btnhome.setText("<< HOME");
        btnhome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnhome.setOpaque(true);
        btnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhomeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btntranshis.setBackground(new java.awt.Color(0, 0, 0));
        btntranshis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btntranshis.setForeground(new java.awt.Color(255, 255, 255));
        btntranshis.setText("Check Transcation History");
        btntranshis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntranshisActionPerformed(evt);
            }
        });

        lbltranshis.setBackground(new java.awt.Color(102, 102, 102));
        lbltranshis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lbltranshis.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbltranshis, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btntranshis)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltranshis, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntranshis, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        btntransmoney.setBackground(new java.awt.Color(0, 0, 0));
        btntransmoney.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btntransmoney.setForeground(new java.awt.Color(255, 255, 255));
        btntransmoney.setText("Transfar Money");
        btntransmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransmoneyActionPerformed(evt);
            }
        });

        lblmoneytrans.setBackground(new java.awt.Color(102, 102, 102));
        lblmoneytrans.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblmoneytrans.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblmoneytrans, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btntransmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmoneytrans, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntransmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblnote.setBackground(new java.awt.Color(0, 0, 0));
        lblnote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblnote.setForeground(new java.awt.Color(255, 255, 255));
        lblnote.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblnote.setText("NOTE : Only Intrabank Transfars are allowed");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnhome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblnote, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblnote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnhome)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhomeActionPerformed
        // TODO add your handling code here:
       refFrame.setVisible(true);
       dispose();

    }//GEN-LAST:event_btnhomeActionPerformed

    private void btntransmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransmoneyActionPerformed
        // TODO add your handling code here:
        Reciverdetails reciverdetails=new Reciverdetails(this,pwdString,acbalString,acidString,nameString);
        reciverdetails.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btntransmoneyActionPerformed

    private void btntranshisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntranshisActionPerformed
        // TODO add your handling code here:
        TransHistory objHistory=new TransHistory(this,acidString);
        objHistory.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btntranshisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfermoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfermoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfermoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfermoney.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfermoney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btntranshis;
    private javax.swing.JButton btntransmoney;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblmoneytrans;
    private javax.swing.JLabel lblnote;
    private javax.swing.JLabel lbltranshis;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
          int x=-100,y=280;
       while(true)
       {
            x=x+5;
           try {
                lblnote.setBounds(x,y ,300 ,20 );
              //  y=y+10;
               
                Thread.sleep(150);
           } catch (Exception e) {
           }
           if(x==420)
           {
               x=-320;
           }
          
       }
    }
}
